export { BaseScraper } from './base'
export { ConnectWetaskiwinScraper } from './connectWetaskiwin'
export { WetaskiwinCaScraper } from './wetaskiwinCa'
export { CentralAlbertaOnlineScraper } from './centralAlbertaOnline'
export type { ScrapedEvent, ScraperConfig } from './base'
